 name: Check URLs

 on: [push]

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: URLs-checker
       uses: actions/URLs-checker@master
       with:
         # The project base path.
         git_path: https://github.com/tinova/docs
          # A comma-separated list of file types to cover in the URL checks
         file_types: .md,.py,.rst

         # Choose whether to include file with no URLs in the prints.
         print_all: False
